version: '2'

services:
  kisiel:
    image: redis
  
  burrito:
    image: redis
    ports:
      - "6370:6379"

  koper:
    image: redis

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
      - "8081:5672"

networks:
  default:
    external:
      name: def_net
