version: '2'

services:
  zeus:
    image: pierewoj/zeus:latest
    depends_on:
    - athena

  athena:
    image: pierewoj/athena:latest

  pieprz:
    image: pierewoj/pieprz:latest
    depends_on:
    - zeus
    - athena

  kalmar:
    image: pierewoj/kalmar:latest
    ports:
      - "8002:8000"

networks:
  default:
    external:
      name: def_net
